---

name: Release Drafter

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: release-drafter/release-drafter@576ba52e425d7702996a1094c4c32c0daca16a41
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
